/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAtChar123workspaceSlugChar125RouteImport } from './routes/_app/@{$workspaceSlug}'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAtChar123workspaceSlugChar125IndexRouteImport } from './routes/_app/@{$workspaceSlug}/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardUsageRouteImport } from './routes/_app/dashboard/usage'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app/dashboard/settings'
import { Route as AppDashboardProvidersRouteImport } from './routes/_app/dashboard/providers'
import { Route as AppDashboardKeysRouteImport } from './routes/_app/dashboard/keys'
import { Route as AppDashboardBillingRouteImport } from './routes/_app/dashboard/billing'
import { Route as AppAtChar123workspaceSlugChar125Char126UsageRouteImport } from './routes/_app/@{$workspaceSlug}/~/usage'
import { Route as AppAtChar123workspaceSlugChar125Char126SettingsRouteImport } from './routes/_app/@{$workspaceSlug}/~/settings'
import { Route as AppAtChar123workspaceSlugChar125Char126MembersRouteImport } from './routes/_app/@{$workspaceSlug}/~/members'
import { Route as AppAtChar123workspaceSlugChar125Char126KeysRouteImport } from './routes/_app/@{$workspaceSlug}/~/keys'
import { Route as AppAtChar123workspaceSlugChar125Char126BillingRouteImport } from './routes/_app/@{$workspaceSlug}/~/billing'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAtChar123workspaceSlugChar125Route =
  AppAtChar123workspaceSlugChar125RouteImport.update({
    id: '/@{$workspaceSlug}',
    path: '/@{$workspaceSlug}',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAtChar123workspaceSlugChar125IndexRoute =
  AppAtChar123workspaceSlugChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardUsageRoute = AppDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardProvidersRoute = AppDashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardKeysRoute = AppDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardBillingRoute = AppDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAtChar123workspaceSlugChar125Char126UsageRoute =
  AppAtChar123workspaceSlugChar125Char126UsageRouteImport.update({
    id: '/~/usage',
    path: '/~/usage',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)
const AppAtChar123workspaceSlugChar125Char126SettingsRoute =
  AppAtChar123workspaceSlugChar125Char126SettingsRouteImport.update({
    id: '/~/settings',
    path: '/~/settings',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)
const AppAtChar123workspaceSlugChar125Char126MembersRoute =
  AppAtChar123workspaceSlugChar125Char126MembersRouteImport.update({
    id: '/~/members',
    path: '/~/members',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)
const AppAtChar123workspaceSlugChar125Char126KeysRoute =
  AppAtChar123workspaceSlugChar125Char126KeysRouteImport.update({
    id: '/~/keys',
    path: '/~/keys',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)
const AppAtChar123workspaceSlugChar125Char126BillingRoute =
  AppAtChar123workspaceSlugChar125Char126BillingRouteImport.update({
    id: '/~/billing',
    path: '/~/billing',
    getParentRoute: () => AppAtChar123workspaceSlugChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/@{$workspaceSlug}': typeof AppAtChar123workspaceSlugChar125RouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/keys': typeof AppDashboardKeysRoute
  '/dashboard/providers': typeof AppDashboardProvidersRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/usage': typeof AppDashboardUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}/': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/@{$workspaceSlug}/~/billing': typeof AppAtChar123workspaceSlugChar125Char126BillingRoute
  '/@{$workspaceSlug}/~/keys': typeof AppAtChar123workspaceSlugChar125Char126KeysRoute
  '/@{$workspaceSlug}/~/members': typeof AppAtChar123workspaceSlugChar125Char126MembersRoute
  '/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/@{$workspaceSlug}/~/usage': typeof AppAtChar123workspaceSlugChar125Char126UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/keys': typeof AppDashboardKeysRoute
  '/dashboard/providers': typeof AppDashboardProvidersRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/usage': typeof AppDashboardUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/@{$workspaceSlug}/~/billing': typeof AppAtChar123workspaceSlugChar125Char126BillingRoute
  '/@{$workspaceSlug}/~/keys': typeof AppAtChar123workspaceSlugChar125Char126KeysRoute
  '/@{$workspaceSlug}/~/members': typeof AppAtChar123workspaceSlugChar125Char126MembersRoute
  '/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/@{$workspaceSlug}/~/usage': typeof AppAtChar123workspaceSlugChar125Char126UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/@{$workspaceSlug}': typeof AppAtChar123workspaceSlugChar125RouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/dashboard/billing': typeof AppDashboardBillingRoute
  '/_app/dashboard/keys': typeof AppDashboardKeysRoute
  '/_app/dashboard/providers': typeof AppDashboardProvidersRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/usage': typeof AppDashboardUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/@{$workspaceSlug}/': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/@{$workspaceSlug}/~/billing': typeof AppAtChar123workspaceSlugChar125Char126BillingRoute
  '/_app/@{$workspaceSlug}/~/keys': typeof AppAtChar123workspaceSlugChar125Char126KeysRoute
  '/_app/@{$workspaceSlug}/~/members': typeof AppAtChar123workspaceSlugChar125Char126MembersRoute
  '/_app/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/_app/@{$workspaceSlug}/~/usage': typeof AppAtChar123workspaceSlugChar125Char126UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/@{$workspaceSlug}'
    | '/dashboard'
    | '/profile'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/providers'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/api/auth/$'
    | '/@{$workspaceSlug}/'
    | '/dashboard/'
    | '/organizations/'
    | '/@{$workspaceSlug}/~/billing'
    | '/@{$workspaceSlug}/~/keys'
    | '/@{$workspaceSlug}/~/members'
    | '/@{$workspaceSlug}/~/settings'
    | '/@{$workspaceSlug}/~/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/profile'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/providers'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/api/auth/$'
    | '/@{$workspaceSlug}'
    | '/dashboard'
    | '/organizations'
    | '/@{$workspaceSlug}/~/billing'
    | '/@{$workspaceSlug}/~/keys'
    | '/@{$workspaceSlug}/~/members'
    | '/@{$workspaceSlug}/~/settings'
    | '/@{$workspaceSlug}/~/usage'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/pricing'
    | '/_app/@{$workspaceSlug}'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/api/health'
    | '/_app/dashboard/billing'
    | '/_app/dashboard/keys'
    | '/_app/dashboard/providers'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/usage'
    | '/api/auth/$'
    | '/_app/@{$workspaceSlug}/'
    | '/_app/dashboard/'
    | '/_app/organizations/'
    | '/_app/@{$workspaceSlug}/~/billing'
    | '/_app/@{$workspaceSlug}/~/keys'
    | '/_app/@{$workspaceSlug}/~/members'
    | '/_app/@{$workspaceSlug}/~/settings'
    | '/_app/@{$workspaceSlug}/~/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}': {
      id: '/_app/@{$workspaceSlug}'
      path: '/@{$workspaceSlug}'
      fullPath: '/@{$workspaceSlug}'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/@{$workspaceSlug}/': {
      id: '/_app/@{$workspaceSlug}/'
      path: '/'
      fullPath: '/@{$workspaceSlug}/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125IndexRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/usage': {
      id: '/_app/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AppDashboardUsageRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/providers': {
      id: '/_app/dashboard/providers'
      path: '/providers'
      fullPath: '/dashboard/providers'
      preLoaderRoute: typeof AppDashboardProvidersRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/keys': {
      id: '/_app/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AppDashboardKeysRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/billing': {
      id: '/_app/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AppDashboardBillingRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/@{$workspaceSlug}/~/usage': {
      id: '/_app/@{$workspaceSlug}/~/usage'
      path: '/~/usage'
      fullPath: '/@{$workspaceSlug}/~/usage'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126UsageRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
    '/_app/@{$workspaceSlug}/~/settings': {
      id: '/_app/@{$workspaceSlug}/~/settings'
      path: '/~/settings'
      fullPath: '/@{$workspaceSlug}/~/settings'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126SettingsRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
    '/_app/@{$workspaceSlug}/~/members': {
      id: '/_app/@{$workspaceSlug}/~/members'
      path: '/~/members'
      fullPath: '/@{$workspaceSlug}/~/members'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126MembersRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
    '/_app/@{$workspaceSlug}/~/keys': {
      id: '/_app/@{$workspaceSlug}/~/keys'
      path: '/~/keys'
      fullPath: '/@{$workspaceSlug}/~/keys'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126KeysRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
    '/_app/@{$workspaceSlug}/~/billing': {
      id: '/_app/@{$workspaceSlug}/~/billing'
      path: '/~/billing'
      fullPath: '/@{$workspaceSlug}/~/billing'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126BillingRouteImport
      parentRoute: typeof AppAtChar123workspaceSlugChar125Route
    }
  }
}

interface AppAtChar123workspaceSlugChar125RouteChildren {
  AppAtChar123workspaceSlugChar125IndexRoute: typeof AppAtChar123workspaceSlugChar125IndexRoute
  AppAtChar123workspaceSlugChar125Char126BillingRoute: typeof AppAtChar123workspaceSlugChar125Char126BillingRoute
  AppAtChar123workspaceSlugChar125Char126KeysRoute: typeof AppAtChar123workspaceSlugChar125Char126KeysRoute
  AppAtChar123workspaceSlugChar125Char126MembersRoute: typeof AppAtChar123workspaceSlugChar125Char126MembersRoute
  AppAtChar123workspaceSlugChar125Char126SettingsRoute: typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  AppAtChar123workspaceSlugChar125Char126UsageRoute: typeof AppAtChar123workspaceSlugChar125Char126UsageRoute
}

const AppAtChar123workspaceSlugChar125RouteChildren: AppAtChar123workspaceSlugChar125RouteChildren =
  {
    AppAtChar123workspaceSlugChar125IndexRoute:
      AppAtChar123workspaceSlugChar125IndexRoute,
    AppAtChar123workspaceSlugChar125Char126BillingRoute:
      AppAtChar123workspaceSlugChar125Char126BillingRoute,
    AppAtChar123workspaceSlugChar125Char126KeysRoute:
      AppAtChar123workspaceSlugChar125Char126KeysRoute,
    AppAtChar123workspaceSlugChar125Char126MembersRoute:
      AppAtChar123workspaceSlugChar125Char126MembersRoute,
    AppAtChar123workspaceSlugChar125Char126SettingsRoute:
      AppAtChar123workspaceSlugChar125Char126SettingsRoute,
    AppAtChar123workspaceSlugChar125Char126UsageRoute:
      AppAtChar123workspaceSlugChar125Char126UsageRoute,
  }

const AppAtChar123workspaceSlugChar125RouteWithChildren =
  AppAtChar123workspaceSlugChar125Route._addFileChildren(
    AppAtChar123workspaceSlugChar125RouteChildren,
  )

interface AppDashboardRouteChildren {
  AppDashboardBillingRoute: typeof AppDashboardBillingRoute
  AppDashboardKeysRoute: typeof AppDashboardKeysRoute
  AppDashboardProvidersRoute: typeof AppDashboardProvidersRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardUsageRoute: typeof AppDashboardUsageRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardBillingRoute: AppDashboardBillingRoute,
  AppDashboardKeysRoute: AppDashboardKeysRoute,
  AppDashboardProvidersRoute: AppDashboardProvidersRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardUsageRoute: AppDashboardUsageRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppAtChar123workspaceSlugChar125Route: typeof AppAtChar123workspaceSlugChar125RouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtChar123workspaceSlugChar125Route:
    AppAtChar123workspaceSlugChar125RouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
