/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationsOrgSlugRouteImport } from './routes/_app/organizations/$orgSlug'
import { Route as AppDashboardUsageRouteImport } from './routes/_app/dashboard/usage'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app/dashboard/settings'
import { Route as AppDashboardKeysRouteImport } from './routes/_app/dashboard/keys'
import { Route as AppDashboardBillingRouteImport } from './routes/_app/dashboard/billing'
import { Route as AppOrganizationsOrgSlugIndexRouteImport } from './routes/_app/organizations/$orgSlug/index'
import { Route as AppOrganizationsOrgSlugSettingsRouteImport } from './routes/_app/organizations/$orgSlug/settings'
import { Route as AppOrganizationsOrgSlugMembersRouteImport } from './routes/_app/organizations/$orgSlug/members'
import { Route as AppOrganizationsOrgSlugBillingRouteImport } from './routes/_app/organizations/$orgSlug/billing'
import { Route as AppOrganizationsOrgSlugWorkspacesIndexRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/index'
import { Route as AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/$workspaceSlug'
import { Route as AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/$workspaceSlug/index'
import { Route as AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
import { Route as AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
import { Route as AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRouteImport } from './routes/_app/organizations/$orgSlug/workspaces/$workspaceSlug/keys'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsOrgSlugRoute = AppOrganizationsOrgSlugRouteImport.update({
  id: '/organizations/$orgSlug',
  path: '/organizations/$orgSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardUsageRoute = AppDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardKeysRoute = AppDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardBillingRoute = AppDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppOrganizationsOrgSlugIndexRoute =
  AppOrganizationsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugSettingsRoute =
  AppOrganizationsOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugMembersRoute =
  AppOrganizationsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugBillingRoute =
  AppOrganizationsOrgSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesIndexRoute =
  AppOrganizationsOrgSlugWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AppOrganizationsOrgSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/keys': typeof AppDashboardKeysRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/usage': typeof AppDashboardUsageRoute
  '/organizations/$orgSlug': typeof AppOrganizationsOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/organizations/$orgSlug/billing': typeof AppOrganizationsOrgSlugBillingRoute
  '/organizations/$orgSlug/members': typeof AppOrganizationsOrgSlugMembersRoute
  '/organizations/$orgSlug/settings': typeof AppOrganizationsOrgSlugSettingsRoute
  '/organizations/$orgSlug/': typeof AppOrganizationsOrgSlugIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/organizations/$orgSlug/workspaces/': typeof AppOrganizationsOrgSlugWorkspacesIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/keys': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/usage': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/keys': typeof AppDashboardKeysRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/usage': typeof AppDashboardUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/organizations/$orgSlug/billing': typeof AppOrganizationsOrgSlugBillingRoute
  '/organizations/$orgSlug/members': typeof AppOrganizationsOrgSlugMembersRoute
  '/organizations/$orgSlug/settings': typeof AppOrganizationsOrgSlugSettingsRoute
  '/organizations/$orgSlug': typeof AppOrganizationsOrgSlugIndexRoute
  '/organizations/$orgSlug/workspaces': typeof AppOrganizationsOrgSlugWorkspacesIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/keys': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/usage': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/dashboard/billing': typeof AppDashboardBillingRoute
  '/_app/dashboard/keys': typeof AppDashboardKeysRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/usage': typeof AppDashboardUsageRoute
  '/_app/organizations/$orgSlug': typeof AppOrganizationsOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/organizations/$orgSlug/billing': typeof AppOrganizationsOrgSlugBillingRoute
  '/_app/organizations/$orgSlug/members': typeof AppOrganizationsOrgSlugMembersRoute
  '/_app/organizations/$orgSlug/settings': typeof AppOrganizationsOrgSlugSettingsRoute
  '/_app/organizations/$orgSlug/': typeof AppOrganizationsOrgSlugIndexRoute
  '/_app/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/_app/organizations/$orgSlug/workspaces/': typeof AppOrganizationsOrgSlugWorkspacesIndexRoute
  '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/keys': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute
  '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/usage': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute
  '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/': typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/profile'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/organizations/$orgSlug'
    | '/api/auth/$'
    | '/dashboard/'
    | '/organizations/'
    | '/organizations/$orgSlug/billing'
    | '/organizations/$orgSlug/members'
    | '/organizations/$orgSlug/settings'
    | '/organizations/$orgSlug/'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug'
    | '/organizations/$orgSlug/workspaces/'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/keys'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/profile'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/api/auth/$'
    | '/dashboard'
    | '/organizations'
    | '/organizations/$orgSlug/billing'
    | '/organizations/$orgSlug/members'
    | '/organizations/$orgSlug/settings'
    | '/organizations/$orgSlug'
    | '/organizations/$orgSlug/workspaces'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/keys'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/pricing'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/api/health'
    | '/_app/dashboard/billing'
    | '/_app/dashboard/keys'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/usage'
    | '/_app/organizations/$orgSlug'
    | '/api/auth/$'
    | '/_app/dashboard/'
    | '/_app/organizations/'
    | '/_app/organizations/$orgSlug/billing'
    | '/_app/organizations/$orgSlug/members'
    | '/_app/organizations/$orgSlug/settings'
    | '/_app/organizations/$orgSlug/'
    | '/_app/organizations/$orgSlug/workspaces/$workspaceSlug'
    | '/_app/organizations/$orgSlug/workspaces/'
    | '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/keys'
    | '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
    | '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organizations/$orgSlug': {
      id: '/_app/organizations/$orgSlug'
      path: '/organizations/$orgSlug'
      fullPath: '/organizations/$orgSlug'
      preLoaderRoute: typeof AppOrganizationsOrgSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/usage': {
      id: '/_app/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AppDashboardUsageRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/keys': {
      id: '/_app/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AppDashboardKeysRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/billing': {
      id: '/_app/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AppDashboardBillingRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/organizations/$orgSlug/': {
      id: '/_app/organizations/$orgSlug/'
      path: '/'
      fullPath: '/organizations/$orgSlug/'
      preLoaderRoute: typeof AppOrganizationsOrgSlugIndexRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/settings': {
      id: '/_app/organizations/$orgSlug/settings'
      path: '/settings'
      fullPath: '/organizations/$orgSlug/settings'
      preLoaderRoute: typeof AppOrganizationsOrgSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/members': {
      id: '/_app/organizations/$orgSlug/members'
      path: '/members'
      fullPath: '/organizations/$orgSlug/members'
      preLoaderRoute: typeof AppOrganizationsOrgSlugMembersRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/billing': {
      id: '/_app/organizations/$orgSlug/billing'
      path: '/billing'
      fullPath: '/organizations/$orgSlug/billing'
      preLoaderRoute: typeof AppOrganizationsOrgSlugBillingRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/': {
      id: '/_app/organizations/$orgSlug/workspaces/'
      path: '/workspaces'
      fullPath: '/organizations/$orgSlug/workspaces/'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesIndexRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/$workspaceSlug': {
      id: '/_app/organizations/$orgSlug/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/': {
      id: '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/usage': {
      id: '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
      path: '/usage'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/usage'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/settings': {
      id: '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/keys': {
      id: '/_app/organizations/$orgSlug/workspaces/$workspaceSlug/keys'
      path: '/keys'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/keys'
      preLoaderRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRouteImport
      parentRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardBillingRoute: typeof AppDashboardBillingRoute
  AppDashboardKeysRoute: typeof AppDashboardKeysRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardUsageRoute: typeof AppDashboardUsageRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardBillingRoute: AppDashboardBillingRoute,
  AppDashboardKeysRoute: AppDashboardKeysRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardUsageRoute: AppDashboardUsageRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren {
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}

const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren: AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren =
  {
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute:
      AppOrganizationsOrgSlugWorkspacesWorkspaceSlugKeysRoute,
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute:
      AppOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute,
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute:
      AppOrganizationsOrgSlugWorkspacesWorkspaceSlugUsageRoute,
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute:
      AppOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute,
  }

const AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren =
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute._addFileChildren(
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren,
  )

interface AppOrganizationsOrgSlugRouteChildren {
  AppOrganizationsOrgSlugBillingRoute: typeof AppOrganizationsOrgSlugBillingRoute
  AppOrganizationsOrgSlugMembersRoute: typeof AppOrganizationsOrgSlugMembersRoute
  AppOrganizationsOrgSlugSettingsRoute: typeof AppOrganizationsOrgSlugSettingsRoute
  AppOrganizationsOrgSlugIndexRoute: typeof AppOrganizationsOrgSlugIndexRoute
  AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute: typeof AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  AppOrganizationsOrgSlugWorkspacesIndexRoute: typeof AppOrganizationsOrgSlugWorkspacesIndexRoute
}

const AppOrganizationsOrgSlugRouteChildren: AppOrganizationsOrgSlugRouteChildren =
  {
    AppOrganizationsOrgSlugBillingRoute: AppOrganizationsOrgSlugBillingRoute,
    AppOrganizationsOrgSlugMembersRoute: AppOrganizationsOrgSlugMembersRoute,
    AppOrganizationsOrgSlugSettingsRoute: AppOrganizationsOrgSlugSettingsRoute,
    AppOrganizationsOrgSlugIndexRoute: AppOrganizationsOrgSlugIndexRoute,
    AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute:
      AppOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren,
    AppOrganizationsOrgSlugWorkspacesIndexRoute:
      AppOrganizationsOrgSlugWorkspacesIndexRoute,
  }

const AppOrganizationsOrgSlugRouteWithChildren =
  AppOrganizationsOrgSlugRoute._addFileChildren(
    AppOrganizationsOrgSlugRouteChildren,
  )

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppOrganizationsOrgSlugRoute: typeof AppOrganizationsOrgSlugRouteWithChildren
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppOrganizationsOrgSlugRoute: AppOrganizationsOrgSlugRouteWithChildren,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
