/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthOrganizationsIndexRouteImport } from './routes/_auth/organizations/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthOrganizationsOrgSlugRouteImport } from './routes/_auth/organizations/$orgSlug'
import { Route as AuthDashboardUsageRouteImport } from './routes/_auth/dashboard/usage'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard/settings'
import { Route as AuthDashboardKeysRouteImport } from './routes/_auth/dashboard/keys'
import { Route as AuthDashboardBillingRouteImport } from './routes/_auth/dashboard/billing'
import { Route as AuthOrganizationsOrgSlugIndexRouteImport } from './routes/_auth/organizations/$orgSlug/index'
import { Route as AuthOrganizationsOrgSlugSettingsRouteImport } from './routes/_auth/organizations/$orgSlug/settings'
import { Route as AuthOrganizationsOrgSlugMembersRouteImport } from './routes/_auth/organizations/$orgSlug/members'
import { Route as AuthOrganizationsOrgSlugBillingRouteImport } from './routes/_auth/organizations/$orgSlug/billing'
import { Route as AuthOrganizationsOrgSlugWorkspacesIndexRouteImport } from './routes/_auth/organizations/$orgSlug/workspaces/index'
import { Route as AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport } from './routes/_auth/organizations/$orgSlug/workspaces/$workspaceSlug'
import { Route as AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/index'
import { Route as AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/settings'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationsOrgSlugRoute =
  AuthOrganizationsOrgSlugRouteImport.update({
    id: '/organizations/$orgSlug',
    path: '/organizations/$orgSlug',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardUsageRoute = AuthDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardKeysRoute = AuthDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardBillingRoute = AuthDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthOrganizationsOrgSlugIndexRoute =
  AuthOrganizationsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugSettingsRoute =
  AuthOrganizationsOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugMembersRoute =
  AuthOrganizationsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugBillingRoute =
  AuthOrganizationsOrgSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugWorkspacesIndexRoute =
  AuthOrganizationsOrgSlugWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute =
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthOrganizationsOrgSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute =
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute =
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/dashboard/billing': typeof AuthDashboardBillingRoute
  '/dashboard/keys': typeof AuthDashboardKeysRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/usage': typeof AuthDashboardUsageRoute
  '/organizations/$orgSlug': typeof AuthOrganizationsOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/organizations/': typeof AuthOrganizationsIndexRoute
  '/organizations/$orgSlug/billing': typeof AuthOrganizationsOrgSlugBillingRoute
  '/organizations/$orgSlug/members': typeof AuthOrganizationsOrgSlugMembersRoute
  '/organizations/$orgSlug/settings': typeof AuthOrganizationsOrgSlugSettingsRoute
  '/organizations/$orgSlug/': typeof AuthOrganizationsOrgSlugIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/organizations/$orgSlug/workspaces/': typeof AuthOrganizationsOrgSlugWorkspacesIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof AuthProfileRoute
  '/dashboard/billing': typeof AuthDashboardBillingRoute
  '/dashboard/keys': typeof AuthDashboardKeysRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/usage': typeof AuthDashboardUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/organizations/$orgSlug/billing': typeof AuthOrganizationsOrgSlugBillingRoute
  '/organizations/$orgSlug/members': typeof AuthOrganizationsOrgSlugMembersRoute
  '/organizations/$orgSlug/settings': typeof AuthOrganizationsOrgSlugSettingsRoute
  '/organizations/$orgSlug': typeof AuthOrganizationsOrgSlugIndexRoute
  '/organizations/$orgSlug/workspaces': typeof AuthOrganizationsOrgSlugWorkspacesIndexRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/dashboard/billing': typeof AuthDashboardBillingRoute
  '/_auth/dashboard/keys': typeof AuthDashboardKeysRoute
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard/usage': typeof AuthDashboardUsageRoute
  '/_auth/organizations/$orgSlug': typeof AuthOrganizationsOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/organizations/': typeof AuthOrganizationsIndexRoute
  '/_auth/organizations/$orgSlug/billing': typeof AuthOrganizationsOrgSlugBillingRoute
  '/_auth/organizations/$orgSlug/members': typeof AuthOrganizationsOrgSlugMembersRoute
  '/_auth/organizations/$orgSlug/settings': typeof AuthOrganizationsOrgSlugSettingsRoute
  '/_auth/organizations/$orgSlug/': typeof AuthOrganizationsOrgSlugIndexRoute
  '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/_auth/organizations/$orgSlug/workspaces/': typeof AuthOrganizationsOrgSlugWorkspacesIndexRoute
  '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/settings': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/': typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/profile'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/organizations/$orgSlug'
    | '/api/auth/$'
    | '/dashboard/'
    | '/organizations/'
    | '/organizations/$orgSlug/billing'
    | '/organizations/$orgSlug/members'
    | '/organizations/$orgSlug/settings'
    | '/organizations/$orgSlug/'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug'
    | '/organizations/$orgSlug/workspaces/'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/profile'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/api/auth/$'
    | '/dashboard'
    | '/organizations'
    | '/organizations/$orgSlug/billing'
    | '/organizations/$orgSlug/members'
    | '/organizations/$orgSlug/settings'
    | '/organizations/$orgSlug'
    | '/organizations/$orgSlug/workspaces'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/organizations/$orgSlug/workspaces/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/pricing'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_auth/dashboard/billing'
    | '/_auth/dashboard/keys'
    | '/_auth/dashboard/settings'
    | '/_auth/dashboard/usage'
    | '/_auth/organizations/$orgSlug'
    | '/api/auth/$'
    | '/_auth/dashboard/'
    | '/_auth/organizations/'
    | '/_auth/organizations/$orgSlug/billing'
    | '/_auth/organizations/$orgSlug/members'
    | '/_auth/organizations/$orgSlug/settings'
    | '/_auth/organizations/$orgSlug/'
    | '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug'
    | '/_auth/organizations/$orgSlug/workspaces/'
    | '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
    | '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/': {
      id: '/_auth/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/organizations/$orgSlug': {
      id: '/_auth/organizations/$orgSlug'
      path: '/organizations/$orgSlug'
      fullPath: '/organizations/$orgSlug'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/usage': {
      id: '/_auth/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AuthDashboardUsageRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/keys': {
      id: '/_auth/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AuthDashboardKeysRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/billing': {
      id: '/_auth/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthDashboardBillingRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/organizations/$orgSlug/': {
      id: '/_auth/organizations/$orgSlug/'
      path: '/'
      fullPath: '/organizations/$orgSlug/'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/settings': {
      id: '/_auth/organizations/$orgSlug/settings'
      path: '/settings'
      fullPath: '/organizations/$orgSlug/settings'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugSettingsRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/members': {
      id: '/_auth/organizations/$orgSlug/members'
      path: '/members'
      fullPath: '/organizations/$orgSlug/members'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugMembersRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/billing': {
      id: '/_auth/organizations/$orgSlug/billing'
      path: '/billing'
      fullPath: '/organizations/$orgSlug/billing'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugBillingRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/workspaces/': {
      id: '/_auth/organizations/$orgSlug/workspaces/'
      path: '/workspaces'
      fullPath: '/organizations/$orgSlug/workspaces/'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugWorkspacesIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug': {
      id: '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugRoute
    }
    '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/': {
      id: '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/settings': {
      id: '/_auth/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/organizations/$orgSlug/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute
    }
  }
}

interface AuthDashboardRouteChildren {
  AuthDashboardBillingRoute: typeof AuthDashboardBillingRoute
  AuthDashboardKeysRoute: typeof AuthDashboardKeysRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardUsageRoute: typeof AuthDashboardUsageRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardBillingRoute: AuthDashboardBillingRoute,
  AuthDashboardKeysRoute: AuthDashboardKeysRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardUsageRoute: AuthDashboardUsageRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren {
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute
}

const AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren: AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren =
  {
    AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute:
      AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugSettingsRoute,
    AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute:
      AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugIndexRoute,
  }

const AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren =
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute._addFileChildren(
    AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteChildren,
  )

interface AuthOrganizationsOrgSlugRouteChildren {
  AuthOrganizationsOrgSlugBillingRoute: typeof AuthOrganizationsOrgSlugBillingRoute
  AuthOrganizationsOrgSlugMembersRoute: typeof AuthOrganizationsOrgSlugMembersRoute
  AuthOrganizationsOrgSlugSettingsRoute: typeof AuthOrganizationsOrgSlugSettingsRoute
  AuthOrganizationsOrgSlugIndexRoute: typeof AuthOrganizationsOrgSlugIndexRoute
  AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute: typeof AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  AuthOrganizationsOrgSlugWorkspacesIndexRoute: typeof AuthOrganizationsOrgSlugWorkspacesIndexRoute
}

const AuthOrganizationsOrgSlugRouteChildren: AuthOrganizationsOrgSlugRouteChildren =
  {
    AuthOrganizationsOrgSlugBillingRoute: AuthOrganizationsOrgSlugBillingRoute,
    AuthOrganizationsOrgSlugMembersRoute: AuthOrganizationsOrgSlugMembersRoute,
    AuthOrganizationsOrgSlugSettingsRoute:
      AuthOrganizationsOrgSlugSettingsRoute,
    AuthOrganizationsOrgSlugIndexRoute: AuthOrganizationsOrgSlugIndexRoute,
    AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRoute:
      AuthOrganizationsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren,
    AuthOrganizationsOrgSlugWorkspacesIndexRoute:
      AuthOrganizationsOrgSlugWorkspacesIndexRoute,
  }

const AuthOrganizationsOrgSlugRouteWithChildren =
  AuthOrganizationsOrgSlugRoute._addFileChildren(
    AuthOrganizationsOrgSlugRouteChildren,
  )

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthOrganizationsOrgSlugRoute: typeof AuthOrganizationsOrgSlugRouteWithChildren
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthOrganizationsOrgSlugRoute: AuthOrganizationsOrgSlugRouteWithChildren,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
